from typing import List, Dict, Optional
from pydantic import BaseModel, Field
from backend.app.schemas.circuit import CircuitState, CircuitExecutionResponse

class ChatMessage(BaseModel):
    role: str = Field(description="'user' or 'assistant'")
    content: str

class TutorChatRequest(BaseModel):
    query: str = Field(description="User natural language question")
    circuit: CircuitState = Field(description="Active quantum circuit JSON state")
    executionResult: Optional[CircuitExecutionResponse] = Field(default=None, description="Simulation outcome data")
    chatHistory: Optional[List[ChatMessage]] = Field(default_factory=list)

class TutorChatResponse(BaseModel):
    response: str = Field(description="Socratic response generated by AI Tutor")
    retrievedDocs: List[str] = Field(default_factory=list, description="Relevant documentation RAG chunks")
    circuitSummary: str = Field(description="Compact summary of active circuit used in prompt")

class DocIngestRequest(BaseModel):
    title: str = Field(min_length=2, max_length=100, description="Title of lecture note / paper / tutorial")
    content: str = Field(min_length=10, description="Full text or LaTeX document content to ingest into RAG vector DB")
